### ISSUE TITLE
 electrum-fair wallet changes bitcoin electrum wallet icon

### ISSUE THREAD

**Issue by TupambaeNet** [FairCoinTeam/electrum-fair#1]
Hi there.

The electrum-fair wallet changed bitcoin electrum wallet icon on a debian wheezy LXDE instalation.
![captura de pantalla de 2015-08-17 21 06 50](https://cloud.githubusercontent.com/assets/1240367/9319369/2a20a646-4524-11e5-89f2-fece9c9ab8f4.png)

**Comment by thokon00** [comment]
Thanks for reporting!

Fixed with bb499c26b3557f43d135da843e56357234f3ca73
