### ISSUE TITLE
The readme doc confuses people to install

### ISSUE THREAD

**Issue by XaviP** [FairCoinTeam/electrum-fair#2]
Maybe it could be better a link to:
https://electrum.fair-coin.org/
or better adapt to faircoin.

**Comment by thokon00** [comment]
Sure, would you like to create a PR? Thanks…

**Comment by XaviP** [comment]
https://github.com/FairCoinTeam/electrum-fair/pull/4

**Comment by thokon00** [comment]
merged, thanks.
